### ISSUE TITLE
其实...作为小白的我觉得还是有必要做一下优化更新的，大佬不能偷懒2333

### ISSUE THREAD

**Issue by ldyivan** [HunterXuan/WeHexo#1]
小白无能为力，只能期望着大佬做下更新什么的了

**Comment by HunterXuan** [comment]
然而小程序现在不会过审的，更新了也没得用 : (

**Comment by ldyivan** [comment]
这样吗，这就很难受了
意思是，以前在用的就还能用，现在新注册小程序已经没得玩了？？

**Comment by HunterXuan** [comment]
大概是的，反正我是没有过审，说是属于资讯性质，个人不能申请 2333

**Comment by MakerGYT** [comment]
通过webhooks与[hexo仓库](https://blog.makergyt.com/)同步，或者说其实与博客构建方式无关，只关注markdown,化繁为简，回归写博文的初衷。
![微信搜索小程序源创智造](https://imgkr.cn-bj.ufileos.com/3cc9ee96-a315-43e0-b9b7-d8a760319ddd.png)
![预览](https://imgkr.cn-bj.ufileos.com/25ec7042-73f7-4c76-8389-d733a609735c.gif)
